title: Antonin Lhuillery
description: >-
  Portfolio de projets et expérimentations.

theme: minima
minima:
  skin: classic        # classic = épuré clair. (autres: dark, solarized…)
  social_links:
    - { platform: github,   user_url: "https://github.com/AntoNainRatio" }
    # - { platform: linkedin, user_url: "https://www.linkedin.com/in/TON-PROFIL" }

header_pages:
  - projects.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true
exclude:
  - README.md
  - CLAUDE.md
